The idp sign in status api
fedidcg/FedCM pull request #345
Opened 2022-09-01 23:46 UTC by samuelgoto

Writes down more formally one of the proposals to address the timing attack problem:

https://github.com/fedidcg/FedCM/issues/230#issuecomment-1233290946

2022-09-01 23:52 UTC, yi-gu commented on spec/index.bs
> +In this variation, the [=user agent=] exposes an API that allows an [=IDP=] to record the user's
s/record/push?

2022-09-01 23:57 UTC, yi-gu commented on spec/index.bs
> +    :   <dfn>signin_url</dfn> (required)
should we make it optional? i.e. if an IDP is not comfortable with browser assisting signing in to IDP (UX concern, security concern etc.), we show a failure UI without this functionality.

2022-09-02 00:04 UTC, yi-gu commented on spec/index.bs
> +        1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-in}} if |accounts|'s size > 0, {{Sign-in Status/signed-out}} otherwise
Does "otherwise" include "no account returned due to reasons like network issues? Should we make it explicit?

2022-09-02 00:05 UTC, samuelgoto commented on spec/index.bs
> +In this variation, the [=user agent=] exposes an API that allows an [=IDP=] to record the user's
"record" seems more appropriate than "push"? "register" maybe?

2022-09-02 00:05 UTC, samuelgoto commented on spec/index.bs
> +    :   <dfn>signin_url</dfn> (required)
Ah, good point, done.

2022-09-02 00:06 UTC, samuelgoto commented on spec/index.bs
> +        1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-in}} if |accounts|'s size > 0, {{Sign-in Status/signed-out}} otherwise
Yes it does. I figure it would be useful to just leave it open for now to avoid low level details. WDYT?

2022-09-02 00:06 UTC, yi-gu commented on spec/index.bs
> +	1. Return an empty list
What does "return an empty list" mean?

2022-09-02 00:08 UTC, samuelgoto commented on spec/index.bs
> +	1. Return an empty list
Returns an "empty accounts list", [].

2022-09-02 00:11 UTC, yi-gu commented on spec/index.bs
> +            NOTE: This happens when the user's local client credentials are invalidated on the server (e.g. changing passwords or deleting accounts on a different device).
s/happens/may happen?
There may be other reasons the account size is 0, e.g. slow network, right?

2022-09-02 00:17 UTC, yi-gu commented on spec/index.bs
> +
Should we add when the Sign-in Status could be reset to `unknown`? e.g. user clearing cookies etc.

2022-09-02 00:20 UTC, yi-gu commented on spec/index.bs
> +In this variation, the [=user agent=] exposes an API that allows an [=IDP=] to record the user's
My concern was it didn't mention "where" to record so "push" implies the UA. Guess "record" would work if we add "in the UA" at the end. WDYT?

2022-09-02 00:21 UTC, yi-gu commented on spec/index.bs
> +        1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-in}} if |accounts|'s size > 0, {{Sign-in Status/signed-out}} otherwise
SG.

2022-09-02 00:22 UTC, yi-gu commented on spec/index.bs
> +	1. Return an empty list
Sorry I mean after we terminate the request, the flow is over so where do we return the empty list to?

2022-09-02 14:37 UTC, bvandersloot-mozilla commented on spec/index.bs
> +        NOTE: This handles the case where the [=IDP=] hasn't had the chance to call the API before the accounts list is needed. This can incur into a [=timing attack=], but it is limited to 1 per [=I
One counterargument that has come to me reading this is that it is also only one instance of friction for the IDP, especially if we set a user as logged in on successful non-empty account list fetch. I would be happier on the privacy end there.

2022-09-02 15:37 UTC, npm1 requested changes

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +Issue: this is a more formal description of what is proposed [here](https://github.com/fedidcg/FedCM/issues/230#issuecomment-1233290946).
This is not an `Issue` per se. Maybe this should be a `Note` instead.

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +A strict subset of the [=push model=] that seems promising is to narrow the pushing to exclusively
```suggestion
A strict subset of the [=push model=] that seems promising is to only push
```

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +almost perfectly (with the exception of server-side invalidations, e.g. users changing passwords or
```suggestion
almost perfectly (with the exception of server-side invalidations, e.g. users changing password, and
```

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +invisibly (i.e. without any explicit and observable indication to the user).
The last statement about impossible to be performed is not really accurate (we still allow it when status is undefined)

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +Internally, each [=user agent=] keeps track of a global <dfn>Sign-in Status</dfn> map per [=IDP=] that can be:
Unclear what this map's key type is. This needs to be more precise, as [=IDP=] is abstract.

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +We would then use the following [=maybe fetch the accounts list=] in the [=potentially create IdentityCredential=] algorithm, as opposed to the [=fetch the accounts list=].
It may be possible to abort even earlier (before the manifest fetch even) if we know the sign in status, no?

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +        1. if |accounts|'s size == 0
```suggestion
        1. If |accounts|'s size is 0:
```

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +            1. Navigate the user to the [=IDP=]'s {{Manifest/signin_url}} to allow them to sign-in.
This is too handwavy. What does navigate mean? Create a new browsing context? Does this unload the existing page?

2022-09-02 15:37 UTC, npm1 commented on spec/index.bs
> +            1. Set |accounts| to the result of the [=fetch the accounts list=] algorithm
This is supposed to happen after the user signed in, I guess? It probably should be in its own task. Also, is there no way for the navigation to signal failure?

2022-09-02 15:47 UTC, samuelgoto commented on spec/index.bs
> +In this variation, the [=user agent=] exposes an API that allows an [=IDP=] to record the user's
I changed from "record" to "signal" and added the "to the user agent" that you suggested.

2022-09-02 15:49 UTC, samuelgoto commented on spec/index.bs
> +	1. Return an empty list
Ah, this returns an empty list to the algorithm that is going to use it, the "potentially create IdentityCredential" which handles gracefully when an empty list is returned. Removed the "terminate the request".

2022-09-02 15:50 UTC, samuelgoto commented on spec/index.bs
> +            NOTE: This happens when the user's local client credentials are invalidated on the server (e.g. changing passwords or deleting accounts on a different device).
Done.

2022-09-02 15:53 UTC, samuelgoto commented on spec/index.bs
> +
Ah, good point. I'm going to leave this as a NOTE for now, because I think we haven't quite thought about this enough.

2022-09-02 15:56 UTC, samuelgoto commented on spec/index.bs
> +invisibly (i.e. without any explicit and observable indication to the user).
Done.

2022-09-02 16:00 UTC, samuelgoto commented on spec/index.bs
> +Internally, each [=user agent=] keeps track of a global <dfn>Sign-in Status</dfn> map per [=IDP=] that can be:
Done.

2022-09-02 16:04 UTC, samuelgoto commented on spec/index.bs
> +        NOTE: This handles the case where the [=IDP=] hasn't had the chance to call the API before the accounts list is needed. This can incur into a [=timing attack=], but it is limited to 1 per [=I
Yeah, agreed.

We use the "unknown" state exclusively for backwards compatibility, but we've been wondering if we would be able to "deprecate it" after some point in time, once IdPs have had a chance to "keep all of the user's sign-in status up to date with the browser".

WDYT?

2022-09-02 16:39 UTC, bvandersloot-mozilla commented on spec/index.bs
> +        NOTE: This handles the case where the [=IDP=] hasn't had the chance to call the API before the accounts list is needed. This can incur into a [=timing attack=], but it is limited to 1 per [=I
It depends on your deprecation timeline. It may make more sense to just have the friction of one more click per-user per-IDP from where we sit. But we are kind of splitting hairs on short-term minor leak vs short-term minor inconvenience here.

 A middle ground may be to make it optional with a note that it will be standardized to  to be removed by a particular sunset date and when the two-click is added to the spec make a successful account fetch after the first click result in a login bit being set.

2022-09-02 17:26 UTC, samuelgoto commented on spec/index.bs
> +            1. Navigate the user to the [=IDP=]'s {{Manifest/signin_url}} to allow them to sign-in.
Yeah, good point. I broke this into a different algorithm and tried to give a high level description. Not super precise quite yet, but a bit more. WDYT?

2022-09-02 17:38 UTC, samuelgoto commented on spec/index.bs
> +            1. Set |accounts| to the result of the [=fetch the accounts list=] algorithm
I broke the step before into its own algorithm and used tasks to be clear about what order this should happen.

WDYT?

2022-09-02 17:54 UTC, samuelgoto commented on spec/index.bs
> +We would then use the following [=maybe fetch the accounts list=] in the [=potentially create IdentityCredential=] algorithm, as opposed to the [=fetch the accounts list=].
Oh, yeah, good point, added another condition here.

I considered breaking down this algorithm into smaller parts so that it integrates better with the "potentially create IdentityCredential" algorithm, but it started getting messy and deviating from the algorithm that we've been using. I think it is helpful to keep the algorithm close to what we've been using for clarity and deal with integrating with the existing algorithms later.

WDYT?

2022-09-02 18:56 UTC, samuelgoto commented on spec/index.bs
> +        NOTE: This handles the case where the [=IDP=] hasn't had the chance to call the API before the accounts list is needed. This can incur into a [=timing attack=], but it is limited to 1 per [=I
Just thinking out loud here, so apologies if this isn't well articulated.

> But we are kind of splitting hairs on short-term minor leak vs short-term minor inconvenience here.

I think I have a different intuition than you do on the level of "minor inconvenience", because if the default value is the `unknown` state, the two-tap interstitial would show, by default, to all of the IDP's users at the moment that they start using the API (so, while it is a small inconvenience for a single user, if you multiple by O(B) of users, that becomes a problem, I think).

> It depends on your deprecation timeline.
> A middle ground may be to make it optional with a note that it will be standardized to to be removed by a particular sunset date

I thought a bit about this, but I'm starting to suspect that we would never be able to fully deprecate / remove the `unknown` state. Consider the following example in the long term:

1. Let's say an IDP has O(M) of users who are already logged in to their services 
2. An IDP decides to make the FedCM integration and starts calling the `IdentityProvider.login()` API.
3. There is a non-zero amount of the IDP's users who are going to be in a state that they **are** logged in (because their sessions are valid) but the IDP has never called the API.

How does an IDP know when "100% of my users that **are** logged in have **also** gone through the explicit `IdentityProvider.login()`"?

One idea that occurs to me is that the IDP could wait until  "the longest expiration time of the last user's session I issued **after** I started calling `IdentityProvider.login()` for new sessions".

We heard from some IdPs that they in practice "never" expire the user's sessions (e.g. google.com cookies are valid for 2 years I think).

So, I think, even long term, we are going to need to be able to represent the state `unknown`.

I think the question then is what to do in that state.

I think one option that is not very controversial is to allow IdPs to:

1. opt-into showing the two-click interstitial on `unknown` or
2. opt-into treating `unknown` as `signed-out` and not show any UI while their users transition from `unknown` to `signed-out`

I'm wondering if we could put the "fetch" under heuristics (e.g. site engagement scores).

> I would be happier on the privacy end there.

You are raising a good point here. 

I don't know what the right balance is here yet, but I have an intuition that I'm leaning towards the "make IdP's deployment easier" end (given the privacy benefit: it is a single-time-per-origin fetch that **also** requires a time fingerprint correlation - that's quite constrained).

More random ramblings than organized thoughts, but WDYT?

2022-09-06 21:51 UTC, npm1 commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-in}}.
The `Sign-in Status` needs to be keyed by some origin presumably? Note that this should probably be some global map which the user agent stores for ~a long time.

2022-09-06 21:51 UTC, npm1 commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-out}}.
ditto need to change the status of some global map

2022-09-06 21:51 UTC, npm1 commented on spec/index.bs
> +    1. Let |status| be the [=Sign-in Status=] of the |provider|.
`provider` is an `IdentityProvider` object that just got created in this page (probably need to compute the origin?)

2022-09-06 21:51 UTC, npm1 commented on spec/index.bs
> +        1. Wait until the [=Sign-in Status=] of the |provider| becomes {{Sign-in Status/signed-in}}
The waits here are simultaneous, so maybe wait until one of the following ... then continue? Also please add a note to point out that this wait means that the website is going to be useless during this time

2022-09-06 21:51 UTC, npm1 commented on spec/index.bs
> +We would then use the following [=maybe fetch the accounts list=] in the [=potentially create IdentityCredential=] algorithm, as opposed to the [=fetch the accounts list=].
Yi's implementation checks the sign in status before fetching the manifest.

2022-09-07 18:30 UTC, samuelgoto commented on spec/index.bs
> +We would then use the following [=maybe fetch the accounts list=] in the [=potentially create IdentityCredential=] algorithm, as opposed to the [=fetch the accounts list=].
Yep, that's covered in the text right now in this sentence: 

```
It would also return early on the [potentially create IdentityCredential](http://localhost:8000/#potentially-create-identitycredential) algorithm if the user was [signed-out](http://localhost:8000/#dom-sign-in-status-signed-out).
```

2022-09-07 18:30 UTC, samuelgoto commented on spec/index.bs
> +            1. Set |accounts| to the result of the [=fetch the accounts list=] algorithm
Done, broke that on a separate algorithm.

2022-09-07 18:34 UTC, samuelgoto commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-in}}.
That's correct. That's written down here:

```
Internally, each [user agent](https://infra.spec.whatwg.org/#user-agent) keeps track of a global Sign-in Status map per [IDP](https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/pull/345.html#idp). The [keys](https://infra.spec.whatwg.org/#map-getting-the-keys) in the [Sign-in Status](https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/pull/345.html#sign-in-status) map is the [origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin) of the [IDP](https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/pull/345.html#idp). The [values](https://infra.spec.whatwg.org/#map-getting-the-values) in the [Sign-in Status](https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/pull/345.html#sign-in-status) map are status objects which can be one of the following values:
```

And used consistently with the state machine maps.

2022-09-07 18:36 UTC, samuelgoto commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-out}}.
it does change the status of the global map, right?

2022-09-07 18:40 UTC, samuelgoto commented on spec/index.bs
> +        1. Wait until the [=Sign-in Status=] of the |provider| becomes {{Sign-in Status/signed-in}}
> The waits here are simultaneous, so maybe wait until one of the following ... then continue?

Done.

> so please add a note to point out that this wait means that the website is going to be useless during this time

I'm assuming you are not suggesting that we block the JS/UI thread, right? That is, unlike prompt() and alert(), we wouldn't be "stopping the JS execution", right?

And if not, I'm also assuming that we don't need to be opinionated about the modality of the dialog in the spec, right? That is, each browser vendor may choose independently how to present this to their users (e.g. some may choose not to make this a modal dialog and "allow the user to still use the website"?)?

2022-09-07 18:43 UTC, samuelgoto commented on spec/index.bs
> +        NOTE: This handles the case where the [=IDP=] hasn't had the chance to call the API before the accounts list is needed. This can incur into a [=timing attack=], but it is limited to 1 per [=I
I think it is going to take us a lot of deployment trial and error here before we understand what the trade-offs are, so I added a note that says "Albeit small, removing this attack surface is an active area of investigation." to be transparent that this is something that we expect to be working on and learning from in the coming months.

With that, resolving this now and will follow up on this challenge.

2022-09-19 15:55 UTC, samuelgoto commented
friendly ping?

2022-09-20 15:13 UTC, npm1 commented on spec/index.bs
> +{{IdentityProviderConfig}}s that the [=Relying Party=] supports and has
Can we decouple this rename from the PR? It seems unrelated. Please send a separate PR for this.

2022-09-20 15:28 UTC, npm1 commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-in}}.
This needs to use a key then?

2022-09-20 15:35 UTC, npm1 commented on spec/index.bs
> +        1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-in}} if |accounts|'s size > 0, {{Sign-in Status/signed-out}} otherwise
```suggestion
        1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-in}} if |accounts| is non-empty, {{Sign-in Status/signed-out}} otherwise
```

2022-09-20 15:35 UTC, npm1 commented on spec/index.bs
> +            1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-out}}
ditto

2022-09-20 18:37 UTC, samuelgoto commented on spec/index.bs
> +{{IdentityProviderConfig}}s that the [=Relying Party=] supports and has
I defined IdentityProvider.login() and IdentityProvider.logout(), which requires me to change this definition (bikeshed complains otherwise). I think that the JS API is an important part of this PR,  so I'd rather keep it.

2022-09-20 18:43 UTC, samuelgoto commented on spec/index.bs
> +        1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-in}} if |accounts|'s size > 0, {{Sign-in Status/signed-out}} otherwise
Ah, good point. Done, here and elsewhere.

2022-09-20 18:43 UTC, samuelgoto commented on spec/index.bs
> +    1. Let |status| be the [=Sign-in Status=] of the |provider|.
Done.

2022-09-20 18:44 UTC, samuelgoto commented on spec/index.bs
> +            1. Return null
Done.

2022-09-20 18:44 UTC, samuelgoto commented on spec/index.bs
> +            1. If they decline, return null
Done.

2022-09-20 18:44 UTC, samuelgoto commented on spec/index.bs
> +            1. Set the [=Sign-in Status=] of the |provider| to {{Sign-in Status/signed-out}}
done.

2022-09-21 22:43 UTC, npm1 commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-in}}.
Still not using key

2022-09-21 22:44 UTC, npm1 commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-out}}.
Ping? Why are you resolving the comments without acting on them

2022-09-21 22:45 UTC, npm1 reviewed
Looks good modulo comments. Also, the change of name of the IdentityProvider dict affects our implementation. We should think if it is necessary, and if it is file a bug to implement this change asap

2022-09-26 21:22 UTC, samuelgoto commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-in}}.
Ah, blargh done now.

2022-09-26 21:22 UTC, samuelgoto commented on spec/index.bs
> +    1. Set the [=Sign-in Status=] to {{Sign-in Status/signed-out}}.
done here too.

2022-09-26 21:26 UTC, samuelgoto commented
> Looks good modulo comments. Also, the change of name of the IdentityProvider dict affects our implementation. We should think if it is necessary, and if it is file a bug to implement this change asap

Seems like we agreed that we should merge this and keep the separation that this is a work in progress with the headers.

PTAL?

2022-09-26 21:58 UTC, npm1 approved these changes

2022-09-26 21:58 UTC, npm1 commented on spec/index.bs
> +Internally, each [=user agent=] keeps track of a global <dfn>Sign-in Status</dfn> map per [=IDP=], initially an empty [=map=]. The [=map/keys=] in the [=Sign-in Status=] map is the [=origin=] of the
It might make sense to move this higher up? It is a bit weird that it is used so much before being defined.

2022-09-27 20:36 UTC, samuelgoto commented on spec/index.bs
> +Internally, each [=user agent=] keeps track of a global <dfn>Sign-in Status</dfn> map per [=IDP=], initially an empty [=map=]. The [=map/keys=] in the [=Sign-in Status=] map is the [=origin=] of the
ah, good point. done!

2022-09-27 21:35 UTC, merged