Rename Manifest to Config
fedidcg/FedCM pull request #369
Opened 2022-10-19 23:01 UTC by samuelgoto

2022-10-20 15:09 UTC, npm1 requested changes

2022-10-20 15:09 UTC, npm1 commented on spec/index.bs
> +The file is parsed expecting [=Config=] JSON object.
```suggestion
The file is parsed expecting a [=Config=] JSON object.
```

2022-10-20 15:09 UTC, npm1 commented on spec/index.bs
> +    1. Let |configUrl| be the result of running [=url parser=] given |configString|.
You are naming this exactly the same as above, and they are not. Please revert.

2022-10-20 15:09 UTC, npm1 commented on spec/index.bs
> +internal config. Imagine a malicious script included by (and running as) the [=RP=] attempting to
Remove internal?

2022-10-20 15:09 UTC, npm1 commented on spec/index.bs
> +When <dfn>computing the config URL</dfn> given an {{IdentityProviderConfig}} |provider| and a
This name is now confusing as it implies we are computing configURL, whereas it is not.

2022-10-20 15:43 UTC, yi-gu commented on spec/index.bs
> +To <dfn>Sign-in to the IDP</dfn> given a [=Config=] |config| and an {{IdentityProviderConfig}}
same here

2023-01-13 17:41 UTC, samuelgoto commented
This is no longer needed, because @npm1 renamed things in his latest PR. Closing this.

2023-01-13 17:41 UTC, closed without merging