Add the IDP sign-in status API to the spec
fedidcg/FedCM pull request #436
Opened 2023-02-14 20:26 UTC by cbiesinger

Explainer: https://github.com/fedidcg/FedCM/blob/main/proposals/idp-sign-in-status-api.md

2023-02-14 20:26 UTC, cbiesinger commented
@bvandersloot-mozilla , can you take a look and see if this makes sense?

2023-02-14 21:01 UTC, samuelgoto reviewed
Looks roughly right to me. Just some minor editorial suggestions, but the algorithm seems right.

2023-02-14 21:23 UTC, martinthomson requested changes
State clearing?

2023-02-14 23:06 UTC, npm1 commented on spec/index.bs
> +header named `IdP-SignIn-Status` containing [[RFC9110#parameter|Parameter]]s.
I think header response names need to be defined. Other than that this checking of all headers in everything sounds like something that needs to be integrated into the Fetch spec (this is a monkeypatch). Perhaps note that as an issue.

2023-02-14 23:06 UTC, npm1 commented on spec/index.bs
> +If that header exists and the first parameter has a name of `action`,
Presumably this needs to be parsed? Can we perhaps encapsulate this in an algorithm

2023-02-14 23:06 UTC, npm1 commented on spec/index.bs
> +    same [=/origin] as the toplevel page, ignore the header.
What do you mean by the origin of the subresource? Presumably the final origin? I think this needs to be pulled from the response itself (I imagine the request may only have the initial origin)

2023-02-14 23:06 UTC, npm1 commented on spec/index.bs
> +    * If the parameter value is `signin`, add (or replace) an entry in the
Use https://infra.spec.whatwg.org/#map-set

2023-02-14 23:06 UTC, npm1 commented on spec/index.bs
> +    * If the parameter value is `signout-all`, add (or replace) an entry in the
ditto

2023-02-15 14:43 UTC, bvandersloot-mozilla commented on spec/index.bs
> +"unknown", "signed-in", and "signed-out".
"<dfn><code>unknown</code></dfn>" is even better

2023-02-15 16:51 UTC, bvandersloot-mozilla commented on spec/index.bs
> +    1. If |signinStatus| is "signed-out", return failure.
Am I following it right that if a user is "signed out", any use of the API fails without a dialog?

2023-02-15 16:52 UTC, bvandersloot-mozilla commented on spec/index.bs
> +        1. If |signinStatus| is "signed-in", show a dialog to the user and return
does this mean that the sign-in status map and the actual state is out of sync at this point?

2023-02-15 16:53 UTC, bvandersloot-mozilla commented
@cbiesinger - what happened to the Javascript API?

2023-02-15 19:08 UTC, cbiesinger reviewed
Martin: I added text that user agents should clear the sign-in state data when cookies or site data is cleared, is that what you meant? If not, please elaborate a bit on your concern

Ben: I was going to do that one separately, do you prefer if I add it to this PR?

2023-02-15 19:08 UTC, cbiesinger commented on spec/index.bs
> +    * If the parameter value is `signout-all`, add (or replace) an entry in the
Done

2023-02-15 19:46 UTC, bvandersloot-mozilla commented
> Ben: I was going to do that one separately, do you prefer if I add it to this PR?
Yes, that would be great!

2023-02-15 19:54 UTC, bvandersloot-mozilla commented on spec/index.bs
> +    1. If |signinStatus| is "signed-out", return failure.
It would be nice to have a way to cleanly recover from a signed-out state without having to navigate to the identity provider independently. This has something to do with how to integrate this with the Multi-IDP patch, since I think their integration is non-trivial.

2023-02-15 20:00 UTC, bvandersloot-mozilla commented on spec/index.bs
> +        1. If |signinStatus| is "signed-in", show a dialog to the user and return
I was confused because showing a sign in link in the dialog when the status was signed-in is non-intuitive to me. I think this makes sense.

2023-02-15 20:22 UTC, cbiesinger commented
I've added the JS API, please take a look!

At a high-level, I think integration with #438 would happen by showing a "sign in" link for each IDP that we have a signed out (or mismatch) status for. I am not sure how to best handle the case when the user is signed out of all IDPs, since the API design so far assumes that no dialog would be shown in such a case.

I'm actually not sure how prescriptive the spec should be with regards to what a sign-in flow should look like, but this PR does add a signin_url field to the config manifest which can be used for that purpose.

2023-02-15 20:38 UTC, cbiesinger commented on spec/index.bs
> +    1. If |signinStatus| is "signed-out", return failure.
I added a "Issue:" for now. I think the multi-IDP PR is maybe a better place to discuss how to integrate these two?

2023-02-15 20:38 UTC, cbiesinger commented on spec/index.bs
> +        1. If |signinStatus| is "signed-in", show a dialog to the user and return
I reworded the note a bit to hopefully make this more clear.

2023-02-15 22:13 UTC, martinthomson commented on spec/index.bs
> +cookies or stored site data.
This isn't sufficiently precise for me.  Yes, if you nuke all state, this needs to go too, but there are other events that cause state for an origin to be removed.  What if only the IdP clears state?  What if only the RP clears state?

2023-02-16 21:31 UTC, cbiesinger commented on spec/index.bs
> +cookies or stored site data.
I elaborated a bit. Not sure I understand the concern about RP state clearing especially but please let me know if the additional text addresses your concern?

2023-02-17 03:24 UTC, martinthomson commented on spec/index.bs
> +    IDP sign-in state changes, it should send an explicit
I don't think that this is true: https://w3c.github.io/webappsec-clear-site-data/

2023-02-17 03:24 UTC, martinthomson commented on spec/index.bs
> +    ::  The user agent must clear the entire map
Missing a period, though I'm not sure whether this is supposed to be a sentence, as it is really a fragment.

2023-02-17 03:24 UTC, martinthomson commented on spec/index.bs
> +            by the deleted cookies.
This is the part that I think needs to be clearer.  It might even need some more thought.

When you clear state for an RP, you probably just forget those identities (and the associated IdPs) that were used.

However, when you clear state for an IdP, there will be a bunch of RPs that have received identity information from the IdP.  I see a two options, each with drawbacks.

1. You could clear ALL state for any RPs as well on the basis that retaining state at the RP might lead to information the RP has could propagate to the IdP, re-establishing same-site recognition when it shouldn't (see below for an attack on this).  The drawback here is that clearing state in one place has an wider effect than users might expect.
2. You could clear just the login state, so that the RP would need to ask again.  The attack here is that, if the user chooses to use the IdP again, the RP could remind the IdP of the user identity.  The drawback is that now clearing state for the IdP ends up having unintended consequences.  And though the reminding thing is a real problem, that only happens if the user gives permission to the RP to use the IdP again AND the RP state is not cleared AND the user intends to have a clean break.  I don't believe that there is anything in FedCM that might leak the information prior to the user performing that grant (with the usual caveats about the effectiveness of cross-site information leakage protections).

Note that in the first case, if you allow for the possibility that each RP might also have established links to other IdPs, then you might also need to clear state for any of those RPs as well.  It's a connected graph and the only way to make clean break is to burn out all the links.  Of course, that might be even more surprising.  At some point though, you need to recognize that this sort of purging needs to consider all forms of linkability, so you might want to stop before the only action you permit involves clearing all browser state.

I don't think that there is an easy cut to make between these two.  I can see how different browsers might choose to take different approaches on the basis that they take different perspectives on how to empower their users.  One option favours user control over privacy, the other favours convenience.  For a specification, we generally try to document the considerations carefully and clearly, then leave these decisions to implementations.  It is OK to do that because there are no guarantees on retention of site-level state, just as there are no firm rules about how private information is managed, so each browser gets to choose their own approach.

Note that I'm talking about a problem with broader scope than your change.  You're the lucky one to have to contend with this.

2023-02-17 04:06 UTC, martinthomson commented on spec/index.bs
> +            by the deleted cookies.
Hmm, the more I think on this, the more I realize that this cuts in both directions.  The only thing that might make the RP clearing case simpler is that we have a different perception of the IdP role in this process.

* If the user deliberately chooses to reuse an identity, then the connection is remade, which is essentially an explicit request to re-establish state.

* If the user chooses a different identity, they may or may not have an expectation that the IdP not share the fact that this RP previously had access to the previous identity.

For the latter, we already rely fairly heavily on the user making a trust decision with respect to the information the IdP might have about them.  That is not a symmetric relationship with the RP.  We don't assume that the user trusts the RP in the same way.

(Lots of stuff to write...)

2023-08-11 20:57 UTC, cbiesinger commented on spec/index.bs
> +    IDP sign-in state changes, it should send an explicit
I have added a section on interactions with Clear-Site-Data.

2023-08-11 21:09 UTC, cbiesinger commented on spec/index.bs
> +            by the deleted cookies.
I have elaborated on the line you commented on to describe the intent I had.

As you say, I think a lot of what you brought up here is only tangentially related to the IDP signin status API (this PR) and applies to FedCM in general.

However, the way I think about it is that the connection between RP and IDP is more akin to a permission. Permissions in general don't get deleted when the user clears cookies... To be honest, I think it would be surprising to users if deleting (e.g.) google.com cookies logged them out of (e.g.) Pinterest and Tripit?

I think I'm going to file a github issue to discuss all this, because it should probably involve not just you and me :)

2023-08-11 21:12 UTC, cbiesinger commented on spec/index.bs
> +            by the deleted cookies.
I filed https://github.com/fedidcg/FedCM/issues/493

2023-08-14 16:22 UTC, samuelgoto commented on spec/index.bs
> +## IDP Sign-in Status ## {#browser-api-idp-sign-in-status}
```suggestion
## The Sign-in Status API ## {#browser-api-sign-in-status}
```

2023-08-14 16:22 UTC, samuelgoto commented on spec/index.bs
> +    1. Let |signinStatus| be the value of the entry in [=IDP Sign-in Status map=]
Also need to get by "type=idp" here.

2023-08-14 16:22 UTC, samuelgoto commented on spec/index.bs
> +      static undefined recordSignOut();
Or maybe we should just have one option or another?

2023-08-14 16:22 UTC, samuelgoto commented on spec/index.bs
> +Issue: Should the recordSign{In,Out} functions return `Promise<undefined>`, so the caller can know
```suggestion
```

Yes, I think it should return Promise<void>.

2023-08-14 16:22 UTC, samuelgoto commented on spec/index.bs
> +Issue: [Reconcile](https://github.com/speced/bikeshed/issues/2636) how these
```suggestion
Issue: [Reconcile](https://github.com/speced/bikeshed/issues/2636) how these
```

Done, I think if you address these comments it will have reconciled with the Login Status API.

2023-08-23 21:17 UTC, cbiesinger reviewed
I think this should be ready for review now

2023-08-23 21:17 UTC, cbiesinger commented on spec/index.bs
> +      static undefined recordSignOut();
I don't think we need two dictionaries at this point. If we decide we want a second one we can easily do so later.

2023-08-23 21:39 UTC, TallTed requested changes
Tiny, human-facing

2023-08-23 21:39 UTC, TallTed commented on spec/index.bs
> +  * If no |options| dictionary is provided, or there is no |idp| member inthe
```suggestion
  * If no |options| dictionary is provided, or there is no |idp| member in the
```

2023-08-23 21:39 UTC, TallTed commented on spec/index.bs
> +    Map=] with the [=map/key=] being  [=/this=]'s [=/relevant settings object=]'s
```suggestion
    Map=] with the [=map/key=] being [=/this=]'s [=/relevant settings object=]'s
```

2023-08-30 21:25 UTC, npm1 commented on spec/index.bs
> +    same [=/origin] as the toplevel page, ignore the header.
```suggestion
    same [=/origin=] as the toplevel page, ignore the header.
```

2023-08-30 21:25 UTC, npm1 commented on spec/index.bs
> +            Note: The user agent may want to reset the state to undefined,
```suggestion
            Note: The user agent may want to reset the state to [=unknown=],
```

2023-08-30 21:25 UTC, npm1 commented on spec/index.bs
> +        Issue: Should the user agent instead show UI to let the user sign
This is not rendering as an issue (maybe needs a blank line before.

2023-08-30 21:25 UTC, npm1 commented on spec/index.bs
> +    1. If the fetch failed, or the size of |accountsList| is 0:
I think fetch failing is being passed as |accountsList| being failure

2023-08-30 21:25 UTC, npm1 commented on spec/index.bs
> +            key being the origin of the configURL and the value being [=signed-out=].
Link origin, link configURL

2023-08-30 21:25 UTC, npm1 commented on spec/index.bs
> +        1. If |signinStatus| is [=signed-in=], show a dialog to the user and return
We (Chrome) don't want to return failure right away here? In this case, we wait until the sign in dialog to resolve, and if we see signin then we refetch accounts?

2023-09-08 19:53 UTC, cbiesinger commented
I've addressed all comments so far. In particular, I have now specified an IDP sign-in flow based on the signin_url. Please take a look, especially @bvandersloot-mozilla and @npm1

2023-09-11 09:54 UTC, TallTed requested changes
Minor but helpful for comprehension: use bullets (`<ul>`) for either/or; use numbers (`<ol>`) for steps/sequences.

2023-09-11 09:54 UTC, TallTed commented on spec/index.bs
> +    1. If |signinStatus| is [=signed-out=], the user agent must either:
```suggestion
    1. If |signinStatus| is [=signed-out=], the user agent must do one of the following:
```

2023-09-11 09:54 UTC, TallTed commented on spec/index.bs
> +        1. Prompt the user whether to continue. This MAY include an affordance
```suggestion
        * Return failure.
        * Prompt the user whether to continue. This MAY include an affordance
```

2023-09-11 09:54 UTC, TallTed commented on spec/index.bs
> +        1. {{IdentityProvider}}.{{IdentityProvider/close}} is called:
```suggestion
        * The user closes the browsing context: return failure.
        * {{IdentityProvider}}.{{IdentityProvider/close}} is called:
```

2023-09-11 12:49 UTC, npm1 reviewed
Some nits up to "show sign-in dialog"

2023-09-11 13:38 UTC, npm1 commented on spec/index.bs
> +See the [=show an IDP sign-in dialog=] algorithm for more details.
Hmm ok so this does nothing if it is invoked and we were not waiting for it to be called, i.e. step "show an IDP sign-in dialog"?

2023-09-11 14:05 UTC, bvandersloot-mozilla commented
Looking at this and a lot has changed since February. Thoughts to start out:
- you probably want a `navigatable` inside of `show an IDP sign-in dialog`.
- the steps for "If signinStatus is[ signed-out ](https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/436/273ccb0...cbiesinger:654908f.html#signed-out), the user agent must either:" are very broad. I _think_ that this will end up working out because the second option includes a user-cancel to failure. 
- Integration with Login Status API is still pending as a big issue. 

Overall, I believe this represents what we agreed would be reasonable in February (although, admittedly that was a long time ago). I would hope we can resolve the log in status integration in person this week at TPAC.

2023-09-20 19:36 UTC, cbiesinger commented
While I work on npm's and Ted's issues, and the TPAC changes:

> * you probably want a `navigatable` inside of `show an IDP sign-in dialog`.

This is done now

> * the steps for "If signinStatus is[ signed-out ](https://pr-preview.s3.amazonaws.com/fedidcg/FedCM/436/273ccb0...cbiesinger:654908f.html#signed-out), the user agent must either:" are very broad. I _think_ that this will end up working out because the second option includes a user-cancel to failure.

Do you want it to say something else? I'm not 100% sure on what your UI will look like here.

> * Integration with Login Status API is still pending as a big issue.

Gladly that was resolved during TPAC. I will comment again once I have updated this PR accordingly. (See also https://github.com/fedidcg/login-status)

2023-09-20 20:44 UTC, cbiesinger reviewed
Addressed the Ted and npm comments, still need to update the header/JS API names

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +            See https://github.com/fedidcg/FedCM/issues/442 for discussion.
Done

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +        |globalObject| (this is the <dfn>fetch config step</dfn>).
Done

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +        and |globalObject| (this is the <dfn>fetch accounts list step</dfn>).
Done.

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
>                  the user is signed in or not and so we may not want to reset
Is that not redundant with "no credentials were sent" in the previous line?

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +            IDP sign-in dialog=] algorithm; this dialog is then the <dfn>confirm
Done

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +                    show a dialog to the user before or after returning failure
I wanted the flexibility to show an error dialog in this case, e.g. if we make this work: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webid/identity_dialog_controller.cc;l=87;drc=b74163d3d63e781ce9899ec6a4e5a7c113d960b9;bpv=1;bpt=1

I am not aware of specific plans from either us or Mozilla, though I also did not specifically ask them.

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +See the [=show an IDP sign-in dialog=] algorithm for more details.
Yeah, do you have a different suggestion? We could make it return a promise and reject it in other cases, not sure that's necessary though.

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +            If the user closes the dialog, return failure.
Done.

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +                1. If |result| is failure, return failure. The user agent MAY
Done.

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +                1. Otherwise, go back to the [=fetch config step=]. As an
Good question. What do you think we should do?

It's not that bad if we keep going, since the user can always cancel.

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +    1. Listen for changes to the [=sign-in status map=] where the key is the
I added a note.

2023-09-20 20:44 UTC, cbiesinger commented on spec/index.bs
> +        |status_changed| to true.
I've simplified this section and that case is now handled.

2023-09-20 21:38 UTC, cbiesinger commented
OK I think this should be fully ready to be reviewed again!

2023-09-21 20:26 UTC, npm1 reviewed
Thanks for working on this!

2023-09-21 20:26 UTC, npm1 commented on spec/index.bs
>      same [=/origin=] as the toplevel page, ignore the header.
I think we need to be more precise about what is the origin. Is this request's currentURL's origin, or something else?

2023-09-21 20:26 UTC, npm1 commented on spec/index.bs
>      same [=/origin=] as the toplevel page, ignore the header.
"toplevel page" is a bit vague, maybe link https://html.spec.whatwg.org/multipage/webappapis.html#concept-environment-top-level-origin

2023-09-21 20:26 UTC, npm1 commented on spec/index.bs
>  * If this is a subresource request, and the response does not have the
"this is a subresource request" is a bit unclear for inside an algorithm. I wonder if this should use https://fetch.spec.whatwg.org/#concept-request-mode, or something else?

2023-09-21 20:26 UTC, npm1 commented on spec/index.bs
> +    * Assert that |value| is a tuple.
The algorithm could return null for example, so this assert seems incorrect.

2023-09-21 20:26 UTC, npm1 commented on spec/index.bs
> +        and the value being [=signed-in=].
Perhaps we change this to `logged-in` / `logged-out`?

2023-09-21 20:26 UTC, npm1 commented on spec/index.bs
> +                1. Otherwise, go back to the [=fetch config step=]. As an
Yea, I suppose that is fine

2023-09-21 20:26 UTC, npm1 commented on spec/index.bs
> +        * {{IdentityProvider}}.{{IdentityProvider/close}} is called:
Called within the context of this new traversable I guess?

2023-09-25 19:41 UTC, cbiesinger commented on spec/index.bs
>  * If this is a subresource request, and the response does not have the
I ended up dropping the subresource part because it's not necessary IMO

2023-09-25 19:41 UTC, cbiesinger commented on spec/index.bs
>      same [=/origin=] as the toplevel page, ignore the header.
Done

2023-09-25 19:41 UTC, cbiesinger commented on spec/index.bs
> +    * Assert that |value| is a tuple.
We only run this algorithm if value is not null, see above.

2023-09-25 19:41 UTC, cbiesinger commented on spec/index.bs
> +        * {{IdentityProvider}}.{{IdentityProvider/close}} is called:
Done

2023-09-25 19:41 UTC, cbiesinger commented on spec/index.bs
> +        and the value being [=signed-in=].
Done

2023-09-26 21:31 UTC, npm1 reviewed
Did a full pass again. Added a bunch of nits but the core algorithms generally look good to me!

2023-09-26 21:31 UTC, npm1 commented on spec/index.bs
> +    1. If |loginStatus| is [=unknown=], [=map/set=] an entry in the [=login
Why not just set the value to logged-in regardless, for simplicity? A user agent can optmize this if needed in their code.

2023-09-26 21:31 UTC, npm1 commented on spec/index.bs
> +        {{IdentityProviderAPIConfig/signin_url}}.
space between the . and signin_url is weird. perhaps change to "|config|'s"

2023-09-26 21:31 UTC, npm1 commented on spec/index.bs
> +See the [=show an IDP sign-in dialog=] algorithm for more details.
I think this is a bit unconventional but probably fine.

2023-09-26 21:31 UTC, npm1 commented on spec/index.bs
> +be finished yet; for example, an IDP may want to prompt the user to verify
nit: link IDPs here and below

2023-09-27 21:30 UTC, cbiesinger reviewed
Please take another look!

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +IDPs can also use a JavaScript API to update the stored sign-in status:
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +When {{NavigatorLogin/setStatus()}} is called with argument |status|:
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +        {{IdentityProviderAPIConfig/signin_url}}.
Fixed by wrapping the line differently

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +be finished yet; for example, an IDP may want to prompt the user to verify
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +        Issue: We should perhaps provide a way to let the RP request that
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +        with the key being the origin of |provider|'s configURL. If there is
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +        * Return failure.
Pretty sure this should be false; done with that.

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +        * Prompt the user whether to continue. This MAY include an affordance
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
>                  the user is signed in or not and so we may not want to reset
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +            If the user closes the dialog, return (failure, true).
Done, but using * instead of 1. because the two steps are mutually exclusive.

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +                1. Otherwise, go back to the [=fetch config step=]. As an
Because the implementation is easier that way? It's what Chrome does...

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +    1. If |loginStatus| is [=unknown=], [=map/set=] an entry in the [=login
Done

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +    1. If |loginStatus| is [=unknown=], [=map/set=] an entry in the [=login
Done. Also linked origin and configURL in the line below.

2023-09-27 21:30 UTC, cbiesinger commented on spec/index.bs
> +* [=map/set|Set=] the entry in the [=Login Status Map=] with the [=map/key=]
Great catch, done.

2023-09-28 14:48 UTC, npm1 reviewed
We should reconcile signin/login somehow.... Not ideal having both sprinkled all over. Any ideas for that?

2023-09-28 14:48 UTC, npm1 commented on spec/index.bs
> +* If the [=/origin=] of the [=current settings object=] is not [=same origin=]
nit: prefer "1."  to "*" as these read sequential?

2023-09-28 14:48 UTC, npm1 commented on spec/index.bs
> +                credentials were sent and therefore the IDP did not learn
[=IDP=]

2023-09-28 14:48 UTC, npm1 commented on spec/index.bs
> +            * If the user closes the dialog, return (failure, true).
I think we need to add to the previous step, before the notes (or a new step): "Wait until one of the following occurs".

2023-09-28 14:48 UTC, npm1 commented on spec/index.bs
> +            * If the [=show an IDP sign-in dialog=] algorithm was triggered:
Then in these we can remove the "If"

2023-09-28 14:48 UTC, npm1 commented on spec/index.bs
>          1. For every |account| in |accountList|, remove |account| from |accountList| if |account|'s
Note that we may remove all accounts if there is none matching the login hint. I think here we need to check if accountsList becomes 0 => then send to the step that creates the confirm idp signin dialog?

2023-09-28 18:52 UTC, cbiesinger reviewed
I changed most signin to login, except for the RP context

2023-09-28 18:52 UTC, cbiesinger commented on spec/index.bs
> +* If the [=/origin=] of the [=current settings object=] is not [=same origin=]
Done

2023-09-28 18:52 UTC, cbiesinger commented on spec/index.bs
> +                credentials were sent and therefore the IDP did not learn
Done

2023-09-28 18:52 UTC, cbiesinger commented on spec/index.bs
> +            * If the user closes the dialog, return (failure, true).
Done, although I think it makes more sense after the notes, because the notes are referencing the paragraph directly above them

2023-09-28 18:52 UTC, cbiesinger commented on spec/index.bs
> +            * If the [=show an IDP sign-in dialog=] algorithm was triggered:
Done

2023-09-28 18:52 UTC, cbiesinger commented on spec/index.bs
>          1. For every |account| in |accountList|, remove |account| from |accountList| if |account|'s
Done

2023-09-28 19:55 UTC, npm1 approved these changes
Some other places where signin/signup is used (no strong opinion on which is correct but figured I would flag:

- Lots of text (intro and first sections) use signin instead of login (though this is probably fine)
- "Request permission to sign-up" (not webexposed, so probably ok?)
- Section 5.5 loginState is set to "SignIn" or "SignUp" (this is returned in the method)

2023-09-28 19:55 UTC, npm1 commented on spec/index.bs
> +    IDP login state changes, it should send an explicit [=Set-Login=] header.
nit: [=IDP=], [=RP=] in this note

2023-09-28 19:55 UTC, npm1 commented on spec/index.bs
> +            1. Wait until one of the following occurs:
Does this need to be a substep of the mismatch dialog step? Or can it just be step 3 (the step after)

2023-09-28 20:04 UTC, cbiesinger reviewed
I did not want to update section 5.5 (webdriver accountlist command) because:
1. That is unrelated to IDP signin status
2. We've shipped those for a while
3. Changing this also requires changing Selenium (https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/federatedcredentialmanagement/FederatedCredentialManagementAccount.java#L54)

2023-09-28 20:04 UTC, cbiesinger commented on spec/index.bs
> +    IDP login state changes, it should send an explicit [=Set-Login=] header.
Done

2023-09-28 20:04 UTC, cbiesinger commented on spec/index.bs
> +            1. Wait until one of the following occurs:
Yes, it needs to be a substep, because all of this only happens if loginStatus is logged-in.

2023-10-03 00:01 UTC, samuelgoto commented on spec/index.bs
> +            1. Otherwise, return failure.
Just wondering: shouldn't we restart the process instead of returning a failure?

2023-10-03 13:07 UTC, bvandersloot-mozilla commented on spec/index.bs
> +                * If the user closes the dialog, return (failure, true).
Why does this return failure immediately?

This allows a user-visible read of the logged in bit.

2023-10-03 13:07 UTC, bvandersloot-mozilla commented on spec/index.bs
> +                    1. Otherwise, go back to the [=fetch config step=]. As an
Let's pick one here.

2023-10-03 18:50 UTC, cbiesinger reviewed
Comments addressed/responded to, please take another looo

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +1. If the [=/origin=] of the [=current settings object=] is not [=same origin=]
I think you're right that we should since in that situation the inner A only gets partitioned (or no) cookies and thus is not aware of the "real" toplevel login state. I have updated this (and also the HTTP header part)

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +Each [=user agent=] keeps a global, persistent <dfn>Login Status
Yes, done.

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +1. [=map/set|Set=] the entry in the [=Login Status Map=] with the [=map/key=]
Done (with a helper variable for origin)

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +        [=Login Status map=] with the key being the origin of the resource
Done

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +                    1. Otherwise, go back to the [=fetch config step=]. As an
Done.

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +    1. [=Create a fresh top-level traversable=] with URL
I added a validation step to fetching the config file to ensure that signin_url is also valid here. I also think that this represents the desired semantics better (don't accept the config file if there is no login_url even if login_url is not triggered during this specific request)

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +User agents must also clear the [=Login Status map=] data when:
Done

2023-10-03 18:50 UTC, cbiesinger commented on spec/index.bs
> +        {{IdentityProviderConfig/configURL}}. If there is no such entry, set it
Done

2023-10-03 19:14 UTC, bvandersloot-mozilla commented on spec/index.bs
> +                * If the user closes the dialog, return (failure, true).
Rejecting in a user-specified time is different than rejecting after a fixed 120s. So by seeing a rejection before that point, the IDP can determine they were not "logged-in".

2023-10-03 19:15 UTC, bvandersloot-mozilla commented on spec/index.bs
> +To <dfn>show an IDP login dialog</dfn> given an {{IdentityProviderAPIConfig}} |config|, run
I meant for instances where the login dialog is in the same navigatable, and then navigate the user back to this page. I think I remember that being out of scope here.

2023-10-03 19:18 UTC, cbiesinger commented on spec/index.bs
> +                * If the user closes the dialog, return (failure, true).
Ah, as of https://github.com/fedidcg/FedCM/commit/c8609ec14b5dde7a4f087e065378b8e457aadbd5 the 120s has been replaced with a random timer.

2023-10-03 19:26 UTC, cbiesinger commented on spec/index.bs
> +To <dfn>show an IDP login dialog</dfn> given an {{IdentityProviderAPIConfig}} |config|, run
I'm not positive I understand you correctly but I think that's out of scope yeah

2023-10-04 08:30 UTC, asr-enid commented on spec/index.bs
> +To <dfn>show an IDP login dialog</dfn> given an {{IdentityProviderAPIConfig}} |config|, run
I guess this refers to flow that require cross origin navigation, for technical reasons or cases with authentication intermediaries which are currently not properly covered by this

2023-10-04 22:46 UTC, samuelgoto commented on spec/index.bs
> +To <dfn>get a login status entry</dfn> for an [=/origin=] |origin|:
Can we move the setter to this list of algorithms too? That way, we can easily just move this section out of this spec into an independent spec, such that Safari/Firefox could implement this spec without necessarily having to implement FedCM.

2023-10-04 22:46 UTC, samuelgoto commented on spec/index.bs
> +1. Otherwise, return a user-agent specific default (either [=unknown=] or
```suggestion
1. Otherwise, return [=unknown=].
```

Can we move the "the user-agent may choose to assume that "unknown" means "logged-out" to the place FedCM consumes this bit? This feels FedCM-specific, e.g. the "user-agent specific value for "unknown" can be different between FedCM and SAA?

2023-10-04 22:46 UTC, samuelgoto commented on spec/index.bs
> +    * If |token| is `logged-in`, [=map/set=] [=Login Status map=][|origin|]
Capture this in a "set" algorithm and use here instead?

2023-10-04 22:46 UTC, samuelgoto commented on spec/index.bs
> +To <dfn>get a login status entry</dfn> for an [=/origin=] |origin|:
```suggestion
To <dfn>get the login status</dfn> for an [=/origin=] |origin|:
```

2023-10-04 22:46 UTC, samuelgoto commented on spec/index.bs
> +        * Prompt the user whether to continue. If the user continues, the user
This is inside the "create an IdentityCredential" algorithm: nothing happens before this, right? That is, "UA prompts user to select an IDP before it does anything" isn't captured **before** we get to this point, right?

2023-10-04 22:46 UTC, samuelgoto commented on spec/index.bs
> +        1. [=map/set|Set=] an entry in the [=Login Status map=] with the
Use a setter algorithm here instead.

2023-10-04 22:46 UTC, samuelgoto commented on spec/index.bs
> +            1. Otherwise, return failure.
Just curious:  does our implementation do? Do we retry?

2023-10-10 21:37 UTC, cbiesinger commented on spec/index.bs
> +To <dfn>get a login status entry</dfn> for an [=/origin=] |origin|:
Done.

2023-10-10 21:37 UTC, cbiesinger commented on spec/index.bs
> +To <dfn>get a login status entry</dfn> for an [=/origin=] |origin|:
Done.

2023-10-10 21:37 UTC, cbiesinger commented on spec/index.bs
> +1. Otherwise, return a user-agent specific default (either [=unknown=] or
Done.

2023-10-10 21:37 UTC, cbiesinger commented on spec/index.bs
> +    * If |token| is `logged-in`, [=map/set=] [=Login Status map=][|origin|]
I did not want to move the mapping of the HTTP token to the enum value to the algorithm, but I did add the set algorithm.

2023-10-10 21:37 UTC, cbiesinger commented on spec/index.bs
> +        1. [=map/set|Set=] an entry in the [=Login Status map=] with the
Done

2023-10-10 23:52 UTC, samuelgoto commented on spec/index.bs
> +            agent SHOULD set |loginStatus| to [=unknown=]. This MAY include an
```suggestion
            agent SHOULD set |loginStatus| to [=unknown=]. This MUST include an
```

Isn't this a MUST? Otherwise, how can we move forward with the algorithm if the loginStatus is 'logged-out'?

2023-10-10 23:53 UTC, samuelgoto commented on spec/index.bs
> +            agent SHOULD set |loginStatus| to [=unknown=]. This MAY include an
Don't we also have to "wait" somewhere here until the user becomes 'logged-in'?

2023-10-10 23:58 UTC, samuelgoto approved these changes
LGTM

2023-10-11 15:23 UTC, cbiesinger commented on spec/index.bs
> +            agent SHOULD set |loginStatus| to [=unknown=]. This MAY include an
That happens if the user triggers the affordance to "show an IDP login dialog" and is encapsulated in that algorithm.

I don't think the SHOULD needs to be a MUST; the algorithm should work fine as-is, no? I left it that way because some user agents don't really want to use an unknown state.

2023-10-11 21:36 UTC, npm1 reviewed
Took another pass. Looks great! Some nits

2023-10-11 21:36 UTC, npm1 commented on spec/index.bs
> +    : the user agent receives a <a http-header>Clear-Site-Data</a> header with a
What happens if this is sent from a subresource or iframe that does not match the top-level? I was trying to find an answer in Clear-Site-Data and it seems the spec is not updated at all to account for any sort of partitioning, but maybe we can at least add an issue to make sure we handle that at some point...

2023-10-11 21:36 UTC, npm1 commented on spec/index.bs
> +        "{{CredentialMediationRequirement/silent}}", return (failure, false).
Why should this be delayed? It seems to me like an issue with the developer call, so no harm rejecting immediately?

2023-10-11 21:36 UTC, npm1 commented on spec/index.bs
> +    1. [=Set the login status=] for the [=/origin] of the
nit:  [=/origin=]

2023-10-11 21:36 UTC, npm1 commented on spec/index.bs
> +    1. Otherwise, if |mediation| is "{{CredentialMediationRequirement/silent}}", return (failure, false).
In this case, we do not delay the rejection so (failure, true)

2023-10-11 21:36 UTC, npm1 commented on spec/index.bs
> +  USVString login_url;
Why is this not required like the other ones? Not that it matters since we don't really use this in JS but still

2023-10-11 21:36 UTC, npm1 commented on spec/index.bs
> +            affordance to [=show an IDP login dialog=]. If the user cancels
nit: this requires parameter

2023-10-11 21:36 UTC, npm1 commented on spec/index.bs
> +            the [=show an IDP login dialog=] algorithm; this dialog is the
nit: parameter for show

2023-10-11 21:39 UTC, npm1 commented on spec/index.bs
> +            1. Let |loginStatus| be the result of [=get the login status=]
Ah, this is a bit weird in the implementation. Because we do not know whether we process the header before the idp.close, we allow header processing to also work. But I guess the spec is sync enough that it's not possible...

2023-10-13 14:52 UTC, cbiesinger reviewed
oops, just realized I did not publish my responses

2023-10-13 14:54 UTC, bvandersloot-mozilla approved these changes

2023-10-13 15:23 UTC, npm1 commented on spec/index.bs
> +1. If the request is not a [=directly user-initiated request=]:
I don't think this is what you want, but rather request's destination = document https://fetch.spec.whatwg.org/#concept-request-destination.

Also the flow in this method is now broken, need to get rid of the "Otherwise".

2023-10-13 15:30 UTC, npm1 approved these changes

2023-10-13 15:30 UTC, merged