Use generic names for the header and JS API
fedidcg/FedCM pull request #494
Opened 2023-08-15 19:59 UTC by cbiesinger

This removes "IDP" from the HTTP header and JS API names so that they are more compatible with the is-logged-in API:
https://github.com/privacycg/is-logged-in

See also https://github.com/privacycg/is-logged-in/pull/54

Open question:
Should the JS API use the exact name in the current is-logged-in explainer (recordLoggedIn) or the more consistent name that this PR uses (recordSignedIn)?

2023-08-15 22:37 UTC, samuelgoto commented
LGTM

@bvandersloot-mozilla wdyt?

2023-08-16 03:31 UTC, TallTed requested changes
Small grammar fixes

2023-08-16 03:31 UTC, TallTed commented on proposals/idp-sign-in-status-api.md
> +In addition, a `IdentityProvider.close()` function is provided to signal to the browser that the
```suggestion
In addition, an `IdentityProvider.close()` function is provided to signal to the browser that the
```

2023-08-16 03:31 UTC, TallTed commented on proposals/idp-sign-in-status-api.md
> +an IDP or not).
```suggestion
In this proposal, we are using generic header and JS function names so that the same API and
headers can be used for is-logged-in while also recording the optional type (i.e., is this
an IDP or not).
```

2023-08-16 03:31 UTC, TallTed commented on proposals/idp-sign-in-status-api.md
> +origin, and marks the current origin as signed in or signed out.
```suggestion
Alternatively, an IdP can call the IdP Sign-in Status API via JS calls through
the static functions `navigator.recordSignedIn({idp: true})` and
`navigator.recordSignedOut({idp: true})`. These are to be called from the IDP's
origin, and mark the current origin as signed in or signed out.
```

2023-08-16 11:39 UTC, bvandersloot-mozilla commented
Yeah, this seems fine until we can get a verdict on Login Status API

2023-08-17 23:46 UTC, merged