Update IDP signin status API explainer
fedidcg/FedCM pull request #505
Opened 2023-09-19 20:20 UTC by cbiesinger

Per discussion at TPAC.

2023-09-19 20:22 UTC, cbiesinger commented
@samuelgoto @martinthomson @bvandersloot-mozilla -- could you sanitycheck that this represents what we discussed?

2023-09-19 20:23 UTC, cbiesinger commented
Also should I rename this to "IDP Login Status API" now, since we changed signin to login in the API?

2023-09-21 16:19 UTC, npm1 reviewed
If we want to keep this updated, I think there are some more changes needed:

* A few places have "signed-in" or "signed-out" where it should use "logged-in" or "logged-out"
* Should the state naming also change?
* The alternatives considered seciton also needs to be updated. In particular, it still mentions "action=signin".

2023-09-21 16:19 UTC, npm1 commented on proposals/idp-sign-in-status-api.md
> +interface NavigatorLogin {
Is this the right name? I see `NavigatorLogin` but elsewhere I saw `Login`

2023-09-21 19:58 UTC, cbiesinger commented on proposals/idp-sign-in-status-api.md
> +interface NavigatorLogin {
As discussed, keeping NavigatorLogin to reduce the risk of naming conflicts with global objects.

I've made the other requested changes

2023-09-21 20:11 UTC, TallTed requested changes

2023-09-21 20:11 UTC, TallTed commented on proposals/idp-sign-in-status-api.md
> +to the IDP, i.e. when this action has logged out all accounts or if this
```suggestion
to the IDP, i.e., when this action has logged out all accounts or if this
```

2023-09-21 20:11 UTC, TallTed commented on proposals/idp-sign-in-status-api.md
> +origin, and mark the current origin as logged in or logged out.
```suggestion
origin, and mark the current origin as logged-in or logged-out.
```

2023-09-25 23:08 UTC, samuelgoto commented on proposals/idp-sign-in-status-api.md
> +SignIn-Status: signin; count=2; type=idp
```suggestion
Set-Login: logged-in;  count=2; type=idp
```

2023-09-25 23:08 UTC, samuelgoto commented on proposals/idp-sign-in-status-api.md
> +SignIn-Status: signout; new-count=1; type=idp
```suggestion
Set-Login: logged-out; new-count=1; type=idp
```

2023-09-25 23:08 UTC, samuelgoto commented on proposals/idp-sign-in-status-api.md
> +SignIn-Status: signin; accountid=foo@bar.com; type=idp
```suggestion
Set-Login: logged-in; accountid=foo@bar.com; type=idp

```

2023-09-25 23:08 UTC, samuelgoto commented on proposals/idp-sign-in-status-api.md
> +SignIn-Status: signout; accountid=foo@bar.com; type=idp
```suggestion
Set-Login: logged-out;  accountid=foo@bar.com; type=idp
```

2023-09-25 23:09 UTC, samuelgoto commented
Just wondering, since there is a lot of duplication between the two explainer, why wouldn't we just point people to this explainer instead [1] for the specifics, and this explainer can go over how FedCM intends to use the signal ?

https://github.com/fedidcg/login-status

2023-09-28 02:54 UTC, TallTed commented on proposals/idp-sign-in-status-api.md
> +the header to support parameters in the future.
```suggestion
with type `item`. For now, we only use bare item part, but this lets us extend
the header to support parameters in the future.
```

2023-09-28 19:06 UTC, cbiesinger reviewed
I addressed the comments.

I added a link to the login status explainer but wanted to keep the two sections in this document so readers don't need to read two documents to understand the proposal.

2023-09-28 19:06 UTC, cbiesinger commented on proposals/idp-sign-in-status-api.md
> +the header to support parameters in the future.
Done

2023-09-28 19:06 UTC, cbiesinger commented on proposals/idp-sign-in-status-api.md
> +SignIn-Status: signin; count=2; type=idp
Done

2023-09-28 19:06 UTC, cbiesinger commented on proposals/idp-sign-in-status-api.md
> +SignIn-Status: signin; accountid=foo@bar.com; type=idp
Done

2023-09-28 19:06 UTC, cbiesinger commented on proposals/idp-sign-in-status-api.md
> +SignIn-Status: signout; accountid=foo@bar.com; type=idp
Done

2023-09-29 17:07 UTC, merged