Keep HOWTO-chrome.md up to date
fedidcg/FedCM pull request #506
Opened 2023-10-03 13:41 UTC by yi-gu

This PR adds two new features and removes the flags requirement for shipped features.

2023-10-03 14:55 UTC, TallTed requested changes

2023-10-03 14:55 UTC, TallTed commented on explorations/HOWTO-chrome.md
> +In order to use the Error API:
```suggestion
To use the Error API:
```

2023-10-03 14:55 UTC, TallTed commented on explorations/HOWTO-chrome.md
> +In order to use the AccountAutoSelectedFlag API:
```suggestion
To use the `AccountAutoSelectedFlag` API:
```

2023-10-03 14:55 UTC, TallTed commented on explorations/HOWTO-chrome.md
> +### AccountAutoSelectedFlag API
```suggestion
### `AccountAutoSelectedFlag` API
```

2023-10-03 15:00 UTC, npm1 commented on explorations/HOWTO-chrome.md
> +Note that the `error` field in the response including both `code` and `url` is optional. As long as the flag is enabled, the browser will render an error UI when the token request is failed. The `err
This is Chrome specific. Please don't say 'the browser', say 'Chrome'. In particular when talking about the customized UI.

2023-10-03 15:00 UTC, npm1 commented on explorations/HOWTO-chrome.md
> +is_account_auto_selected=true&account_id=123&client_id=client1234&nonce=Ct60bD&disclosure_text_shown=true
The new one should go at the end?

2023-10-03 15:06 UTC, cbiesinger commented on explorations/HOWTO-chrome.md
> +Note that the `error` field in the response including both `code` and `url` is optional. As long as the flag is enabled, the browser will render an error UI when the token request is failed. The `err
Maybe wrap this line?

2023-10-03 19:41 UTC, yi-gu commented on explorations/HOWTO-chrome.md
> +```
Not sure if the indentation is necessary given that the snippet is rendered by markdown. Keeping it as-is to be consistent with the rest of the doc. Feel free to reopen it. Thanks!

2023-10-03 23:53 UTC, kdenhartog commented on explorations/HOWTO-chrome.md
> +For IdP, the browser will include the boolean `is_account_auto_selected` in the request sent to the id assersion endpoint:
```suggestion
For IdP, the browser will include the boolean `is_account_auto_selected` in the request sent to the id assertion endpoint:
```

2023-10-03 23:53 UTC, kdenhartog commented on explorations/HOWTO-chrome.md
> +For the API caller, the browser will include the boolean `isAccountAutoSelected` when resolving the promise with the token:
```suggestion
For the Relying Party, the browser will include the boolean `isAccountAutoSelected` when resolving the promise with the token:
```

Thinking this might be more consistent language here, but not certain.

2023-10-03 23:53 UTC, kdenhartog commented on explorations/HOWTO-chrome.md
> +  "isAccountAutoSelected": true
providing this information seems like it would be unnecessary. What's the motivation for indicating this to the RP/IDP rather than just making this a client side only piece of information? Say for example, that the user doesn't auto select an account could that reveal information about whether or not it's a temp account versus a primary permanent account based on statistical analysis?

2023-10-03 23:58 UTC, yi-gu commented on explorations/HOWTO-chrome.md
> +For the API caller, the browser will include the boolean `isAccountAutoSelected` when resolving the promise with the token:
While it's true that API is called on the RP site, the API caller could be the RP itself or the IdP (via SDK) or 3P library that uses FedCM API.

2023-10-04 00:02 UTC, yi-gu commented on explorations/HOWTO-chrome.md
> +  "isAccountAutoSelected": true
Could you elaborate a bit on the attacking vector here? I'm not sure if I understand what you meant by temp account v.s. primary account. The boolean can only be true for "returning" account which means that the user has used that account in this browser client in the past.

For motivation and privacy & security considerations, please see https://github.com/fedidcg/FedCM/issues/497

2023-10-04 01:10 UTC, kdenhartog commented on explorations/HOWTO-chrome.md
> +  "isAccountAutoSelected": true
Thanks, I'll have to give a read into this a bit further. I wasn't aware of the linked issue before this, but just came across it. Do you guys have a glitch.me demo of this feature built by chance? I'd like to play around with this feature a bit more to make sure I'm understanding the goals and am able to assess the potential impact correctly.

FWIW, don't block this on my review but my hunch does think this is probably oversharing information. If I come up with a practical attack then it could always be reverted later too.

2023-10-04 01:56 UTC, yi-gu commented on explorations/HOWTO-chrome.md
> +  "isAccountAutoSelected": true
You could try https://webid-fcm.glitch.me after enabling the flag. The boolean will be displayed in the log section.
Note: in Chrome, after auto re-authen is triggered, it will be suppressed for 10 mins (or until a user explicitly signs in).

2023-10-04 15:29 UTC, npm1 approved these changes

2023-10-04 15:29 UTC, npm1 commented on explorations/HOWTO-chrome.md
> +  "isAccountAutoSelected": true
Hey Kyle, ok with us merging this howto change or do you have any further comment?

2023-10-12 18:28 UTC, TallTed requested changes

2023-10-12 18:28 UTC, TallTed commented on explorations/HOWTO-chrome.md
> +To use the IdentityCredentialAutoSelectedFlag API:
```suggestion
To use the `IdentityCredentialAutoSelectedFlag` API:
```

2023-10-12 18:28 UTC, TallTed commented on explorations/HOWTO-chrome.md
> +request sent to the id assersion endpoint:
```suggestion
request sent to the ID assertion endpoint:
```

2023-10-17 13:36 UTC, yi-gu commented on explorations/HOWTO-chrome.md
> +request sent to the id assersion endpoint:
Thanks! Done.

2023-10-17 14:04 UTC, npm1 approved these changes

2023-10-17 14:34 UTC, yi-gu commented on explorations/HOWTO-chrome.md
> +To use the IdentityCredentialAutoSelectedFlag API:
Thanks! Not sure if this is needed given the context. Will keep it as-is to be consistent with the rest of the file. Please feel free to reopen if you feel strongly about it or if there's a style guide for this.

2023-10-17 16:31 UTC, asr-enid commented on explorations/HOWTO-chrome.md
>  * Enable the experimental feature `FedCmRpContext` in `chrome://flags`.
This is generally available since 116 isn't it?

2023-10-17 16:31 UTC, asr-enid commented on explorations/HOWTO-chrome.md
>  * Enable the experimental feature `FedCmRpContext` in `chrome://flags`.
See https://developer.chrome.com/docs/privacy-sandbox/fedcm-updates/

2023-10-17 16:31 UTC, asr-enid commented on explorations/HOWTO-chrome.md
>  * Enable the experimental feature `FedCmLoginHint` in `chrome://flags`.
Isn't this generally available since 116 - see https://developer.chrome.com/docs/privacy-sandbox/fedcm-updates/

2023-10-17 16:31 UTC, asr-enid commented on explorations/HOWTO-chrome.md
>  * Enable the experimental feature `FedCmLoginHint` in `chrome://flags`.
Isn't this generally available since 116 - see https://developer.chrome.com/docs/privacy-sandbox/fedcm-updates/

2023-10-17 16:35 UTC, yi-gu commented on explorations/HOWTO-chrome.md
>  * Enable the experimental feature `FedCmRpContext` in `chrome://flags`.
Good call. Guess I can remove them in this PR.

2023-10-18 19:09 UTC, npm1 approved these changes

2023-10-18 19:09 UTC, merged