Add a disconnect method
fedidcg/FedCM pull request #515
Opened 2023-11-16 23:09 UTC by npm1

Fixes https://github.com/fedidcg/FedCM/issues/496. Adds a `disconnect_endpoint` and a `disconnect` method to allow the RP to request the IDP to disconnect a previously connected federated account. I opted for `disconnect_endpoint` instead of `disconnection_endpoint` because it sounded a bit better to me, but open to change it. The credentialed request is sent with IDP cookies but using CORS as the request mode. If no account is found or there is some other error, the user agent removes all connections associated with the RP, IDP.

2023-11-17 18:00 UTC, TallTed requested changes
Small stuff for clarity

2023-11-17 18:00 UTC, TallTed commented on spec/index.bs
> +Issue: the [=connected accounts set=] should be double keyed in the [=RP=] (e.g. it should include
```suggestion
Issue: the [=connected accounts set=] should be double keyed in the [=RP=] (i.e., it should include
```

2023-11-17 18:00 UTC, TallTed commented on spec/index.bs
> +{{IdentityCredentialDisconnectOptions}} |options| perform the following steps:
```suggestion
When the static {{IdentityCredential/disconnect}} method is invoked, given an
{{IdentityCredentialDisconnectOptions}} |options|, perform the following steps:
```

2023-11-20 16:33 UTC, npm1 commented
Ping

2023-11-20 16:59 UTC, yi-gu commented on spec/index.bs
> +    1. Assert: these steps are running [=in parallel=].
Maybe I misunderstood: the following steps are still sequential, right? e.g. you have to fetch `configUrl` first before parsing `disconnectUrl` etc.

2023-11-20 17:09 UTC, npm1 commented on spec/index.bs
> +    1. Assert: these steps are running [=in parallel=].
Right, that is not what in parallel means. If you click the link it says what it actually means https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel

2023-11-20 17:09 UTC, yi-gu commented on spec/index.bs
> +[=user agent=] to disconnect the account from the [=connected accounts set=].
I know it was mentioned above but should we call out here that all accounts associated with the RP will be disconnected if something is wrong here?

2023-11-20 17:24 UTC, yi-gu commented on spec/index.bs
> +    1. Assert: these steps are running [=in parallel=].
ah got it.

2023-11-20 17:25 UTC, yi-gu commented
lgtm

2023-11-20 17:37 UTC, npm1 commented on spec/index.bs
> +[=user agent=] to disconnect the account from the [=connected accounts set=].
Added

2023-11-28 21:01 UTC, cbiesinger approved these changes

2023-11-29 18:00 UTC, samuelgoto commented on spec/index.bs
> +        1. If |rp| equals |rpOrigin| and |idp| equals |idpOrigin|, [=list/remove=] |triple| from the
Same here. Lets abstract this away from the callers.

2023-11-29 20:13 UTC, npm1 commented on spec/index.bs
> +        |config|["{{IdentityProviderAPIConfig/disconnect_endpoint}}"], and |globalObject|.
Ok

2023-11-29 20:13 UTC, npm1 commented on spec/index.bs
> +            1. [=list/Remove=] |triple| from the [=connected accounts set=].
Done

2023-11-29 21:15 UTC, samuelgoto commented on spec/index.bs
> +        "{{NetworkError}}" {{DOMException}}.
hummm there is something off here i think .... we throw a NetworkError, but the [=Send a disconnect request=] actually succeeded. The |foundAccount| wasn't found within the internals of the browser, but the actual request succeeded ... i can't quite put my finger on what's wrong here, but this feels off to me: it feels like the actual promise succeeded: the network request was made successfully, the connected set was updated correctly (by removing *any* account), etc,  but we are telling the RP that there was an error?

2023-11-29 21:57 UTC, npm1 commented on spec/index.bs
> +        * {{IdentityCredentialDisconnectOptions/accountHint}}
This is checking whether or not they are empty, eg. having `configUrl: ""` as opposed to not having it at all. Do you think we should remove this check altogether?

2023-11-29 21:57 UTC, npm1 commented on spec/index.bs
> +        "{{NetworkError}}" {{DOMException}}.
Oh yes I actually want this to depend on whether IdP disconnection server-side succeeded or not. PTAL?

2023-11-29 21:57 UTC, npm1 commented on spec/index.bs
> +    1. If |accountId| is not failure:
Done

2023-11-29 22:09 UTC, samuelgoto commented on spec/index.bs
> +        * {{IdentityCredentialDisconnectOptions/accountHint}}
> This is checking whether or not they are empty, eg. having configUrl: "" as opposed to not having it at all. 

```
If |options| does not [=map/contain=] all of the following, then throw a new {{TypeError}}:
```

[=map/contain=] just checks for the presence of the key though, not for whether its value is empty-string, right?

> Do you think we should remove this check altogether?

Don't we already fallback gracefully when those values are empty-strings further down into the algorithms?

2023-11-29 22:15 UTC, npm1 commented on spec/index.bs
> +        * {{IdentityCredentialDisconnectOptions/accountHint}}
? I think you are not looking at the latest commits? "If any of the following members from |options| are empty". I think configURL we would fail, less clear for clientId and accountHint (we'd at least send fetches, eg fail later than we should)

2023-11-29 22:17 UTC, samuelgoto commented on spec/index.bs
> +        |accountId| be the result.
```suggestion
        |result| be the result.
```

I'm having a hard time parsing this algorithm here under the assumption that |accountId| can be a failure. I'd suggest we rename this to |result|, and check for failure early on and if no failure, assign |result| to a new variable |accountId|.

For example:

```
1. If |result| is failure
    1. [=remove all connections=] given |rpOrigin| and |idpOrigin|.
    1. [=reject=] |promise| with a "{{NetworkError}}" {{DOMException}}.
1. Let |accountId| be |result|. // carries on assuming there wasn't a network error
```

2023-11-29 22:17 UTC, samuelgoto commented on spec/index.bs
> +    1. Let |wasAccountRemoved| be false.
```suggestion
```

Is this really necessary? You are already assigning wasAccountRemoved in the next step as the result of the [=remove the connection=] algorithm?

2023-11-29 22:17 UTC, samuelgoto commented on spec/index.bs
> +        "{{NetworkError}}" {{DOMException}}.
I think this looks better, but I made a few suggestions to try to return early when a network error occurs, so that it becomes easier to reason about the non-error cases. WDYT?

2023-11-29 22:17 UTC, samuelgoto commented on spec/index.bs
> +To <dfn>remove all connections</dfn> given |rpOrigin| and |idpOrigin|, run the following steps:
I really like the separation here between the two algorithms: removing the connection by accountId and removing all connections.

2023-11-29 22:21 UTC, samuelgoto commented on spec/index.bs
> +        * {{IdentityCredentialDisconnectOptions/accountHint}}
Do we really care if they are empty? Can't we make the disconnect network request call without them? This seems like an artificial requirement that Rps are going to put garbage in (like "client_id=foobar", "accountHint=goaway) just to make this work.

That is, the disconnect network call is already responsible for handling requests where client_id or accountHint doesn't match anything in their servers, I'm wondering if we should just get out of the way here, as opposed to checking for the empty-ness of the strings here.

2023-11-29 22:50 UTC, npm1 commented on spec/index.bs
> +To <dfn>remove all connections</dfn> given |rpOrigin| and |idpOrigin|, run the following steps:
Thanks

2023-11-29 22:50 UTC, npm1 commented on spec/index.bs
> +        * {{IdentityCredentialDisconnectOptions/accountHint}}
Sure, I think we can remove these checks then

2023-11-29 22:50 UTC, npm1 commented on spec/index.bs
> +        |accountId| be the result.
Done

2023-11-29 22:50 UTC, npm1 commented on spec/index.bs
> +        "{{NetworkError}}" {{DOMException}}.
Applied the suggestions, thanks!

2023-11-29 22:59 UTC, samuelgoto approved these changes

2023-11-29 22:59 UTC, samuelgoto commented
LGTM

@bvandersloot-mozilla WDYT?

2023-11-30 18:24 UTC, TallTed commented on spec/index.bs
> +To <dfn>remove the connection</dfn> given |accountId|, |rpOrigin|, and |idpOrigin|, run the
```suggestion
To <dfn>remove a connection</dfn>: given |accountId|, |rpOrigin|, and |idpOrigin|, run the
```

2023-11-30 18:26 UTC, TallTed commented on spec/index.bs
> +    1. [=Remove the connection=] given |accountId|, |rpOrigin|, and |idpOrigin| and let
```suggestion
    1. [=Remove a connection=] using |accountId|, |rpOrigin|, and |idpOrigin|, and let
```

2023-11-30 18:31 UTC, bvandersloot-mozilla commented
I think I follow and LGTM.

2023-11-30 18:48 UTC, samuelgoto commented
> I think I follow and LGTM.

Thanks @bvandersloot-mozilla ! @npm1 i'll wait for you to resolve the last remaining bits of feedback from @TallTed and then squash and merge.

2023-12-01 19:21 UTC, merged