Add list of FPWD critical issues
fedidcg/FedCM pull request #623
Opened 2024-07-16 15:23 UTC by wseltzer

List the issues that, before publication of the FPWD, the WG and CG identified to be considered before CR publication.

2024-07-16 15:25 UTC, wseltzer commented
This list of issues: https://github.com/fedidcg/FedCM/issues?q=is%3Aissue+is%3Aopen+label%3AFPWD+sort%3Acreated-asc

2024-07-16 19:05 UTC, samuelgoto approved these changes
LGTM

2024-07-16 19:08 UTC, npm1 approved these changes

2024-07-20 23:00 UTC, martinthomson commented on spec/index.bs
> +Note: The WG has labeled the following issues as critical open issues that must be considered before publication of a Candidate Recommendation.
```suggestion
Note: The WG has labeled the following issues as critical open issues that must be resolved before publication of a Candidate Recommendation.
```

2024-07-21 02:32 UTC, martinthomson requested changes
I assert that "consideration" is too weak for this.  These need resolutions that are backed by consensus.

2024-07-29 15:23 UTC, wseltzer commented
> I assert that "consideration" is too weak for this. These need resolutions that are backed by consensus.

That's consistent with the [W3C Process](https://www.w3.org/policies/process/#transition-reqs) requirement that the group "MUST [formally address](https://www.w3.org/policies/process/#formally-addressed) all issues raised about the document since the previous [maturity stage](https://www.w3.org/policies/process/#maturity-stages)."

2024-07-30 16:25 UTC, wseltzer commented
On the 30 July WG call, it was suggested to adopt the language directly from the W3C Process, "formally addressed." PR updated accordingly.

2024-08-06 15:01 UTC, samuelgoto commented on spec/index.bs
> +Note: The WG has labeled the following issues as critical open issues that must be formally addressed before publication of a Candidate Recommendation.
I'm still seeing issues in this [label](https://github.com/fedidcg/FedCM/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3Achrome) that isn't represented in this [label](https://github.com/fedidcg/FedCM/issues?q=is%3Aissue+is%3Aopen+label%3AFPWD+sort%3Acreated-asc), or in this PR.

Can I assume that these will eventually match up?

2024-08-06 17:26 UTC, wseltzer commented on spec/index.bs
> +Note: The WG has labeled the following issues as critical open issues that must be formally addressed before publication of a Candidate Recommendation.
Thanks Sam, https://github.com/fedidcg/FedCM/pull/630 adds these issues to the list.

2024-08-06 21:32 UTC, wseltzer commented
[Updated call for consensus](https://lists.w3.org/Archives/Public/public-fedid-wg/2024Aug/0001.html) until 13 August.

2024-08-06 21:33 UTC, samuelgoto commented on spec/index.bs
> +Note: The WG has labeled the following issues as critical open issues that must be formally addressed before publication of a Candidate Recommendation.
LGTM

2024-08-06 21:33 UTC, samuelgoto approved these changes

2024-08-07 16:01 UTC, bvandersloot-mozilla commented
> > I assert that "consideration" is too weak for this. These need resolutions that are backed by consensus.
> 
> That's consistent with the [W3C Process](https://www.w3.org/policies/process/#transition-reqs) requirement that the group "MUST [formally address](https://www.w3.org/policies/process/#formally-addressed) all issues raised about the document since the previous [maturity stage](https://www.w3.org/policies/process/#maturity-stages)."

That works as well for Mozilla

2024-08-14 15:41 UTC, merged